rm(list=ls())
library(mlr3) #cant get mlr3 to install on work computer
library(xgboost)
#install.packages("mlr3learners")
library(mlr3learners)
library(mlr3verse)
library(mlr3fselect)
library("mlr3hyperband")
library(fastDummies)

#library(doParallel)
#all_cores <- parallel::detectCores(logical = FALSE)
#registerDoParallel(cores = all_cores)

set.seed(666)

###########################
#Input and minor wrangling#
###########################

#Usage is predictor matrix, multinomial matrix, integer, taxatomodel (possibles)
#The integer is used to pull a line from a file that has all the taxa to model

#inargs <- commandArgs(trailingOnly = TRUE)

#NOTE a lot of feature engineering happened in the neural network program
#I have avoided redoing that here for convenience. 
#X <- read.csv(inargs[1]) #e.g., "./imputed_scaled_ITS_metadata.csv"

#Bring in taxon proportions, these were wrangled in R after being generated by CNVRG
# taxa <- read.csv(inargs[2]) #./ITSp_estimates_wrangled_for_post_modeling_analysis_divided_by_ISD.csv
# possibles <- read.csv(inargs[4]) # "./processedData/ITS_taxa_to_model_via_randomforest.csv"
# focal_taxon <- possibles[inargs[3],]

#stdout qc
for(i in 1:4){
  print(inargs[i])
}
print(focal_taxon)

#Debugging stuff
taxa <- read.csv("./processedData//ITSp_estimates_wrangled_for_post_modeling_analysis_divided_by_ISD.csv")
 possibles <- read.csv("./processedData/ITS_taxa_to_model_via_randomforest.csv")
 focal_taxon <- possibles[2,]
 
 X<- read.csv("./processedData/ITSmetadat_wrangled_for_post_modeling_analysis.csv")
 X <- X[X$substrate == "plant",]

#######################
# Feature engineering #
 ######################
X <- X[,names(X) != "shannonsISD"] #remove microbial diversity

#Make a leaf density variable
X$sla = X$mass_extracted_g / X$area_cm2

#Select only the features that I care about
#only a single one of a group of highly correlated features was chosen
#e.g., absorbance measurements were redundant in some cases.
#See the correlagram.R script
X <- X[,names(X) %in% c(
  "absorbance_420",
  "absorbance_940", 
  "area_cm2",
  "Ambient_Humidity",
  "Ambient_Temperature",
  "B",
  #"canopyCover" , #Not sure where my measurement of this went. Maybe I didn't mak them?
  "circumStem",
  "compartment", #check this out
  "contactless_temp",
  "deadDown",
  "densitometer",
  "ecs_initial",
  "ecs_max",
  "elev_m",
  "FmPrime",
  "FoPrime",
  "Fs",
  "FvP.FmP",
  "G",
  "gH.",
  "habit", 
  "height_sample",
  "julianDate",
  "Latitude",
  "Leaf_Temp_Differential",
  "LEF",
  "leaves_extracted",
  "Light_Intensity..PAR.",
  "Longitude",
  "mass_extracted_g",
  "mean_temp_april.y" ,          
  "MEM1.y",
  "MEM2.y",
  "NPQt_MPF",
  "phenology",
  "Phi2",
  "PhiNO",
  "PhiNPQ",
  "plant_vol",
  "precip_april_in.x",
  "pressure",
  "qL",
  "R",
  "Rel_Chl_intensity",
  "Relative_Chlorophyll",
  "RFd",
  "sample",
  "shannons_flora",
  "shrubRich",
  #"sidePlantSampled",
  "sla",
  "slope_perc",
  "SPAD_420_intensity",
  "SPAD_420",
  "thickness",
  "TimeofDay",
  "taxon_final",
  "toughness",
  "treeRich",
  "waterRetention"
)]

#Convert partial leaf to 0.5
X$leaves_extracted <- (as.character(X$leaves_extracted))
X$leaves_extracted[X$leaves_extracted == "partial"] <- 0.5
X$leaves_extracted <- (as.numeric(X$leaves_extracted))

X$waterRetention <- (as.character(X$waterRetention))
indices <- which(X$waterRetention == "90+")
X$waterRetention[indices] <- 90
X$waterRetention <- (as.numeric(X$waterRetention))

#Do dummy encoding of all host taxa and other categoricals
#Writing out all the categorical features for clarity
categoricals <- c(
  "habit",
  "compartment",
  "taxon_final",
  "phenology"
)
X <- dummy_cols(.data = X, select_columns = categoricals)

table(X$sample %in% taxa$sample)
table(taxa$sample %in%  X$sample )

#the missing stuff were things I removed due to poor sequencing
dim(X)
dim(taxa)
merged_dat <- merge(X, taxa, by.x = "sample", by.y = "sample", all.y = T)
dim(merged_dat)

#Making a response object for readability
response_taxon <- merged_dat[, names(merged_dat) == focal_taxon]

#Get rid of stuff we don't need in merged_dat 
#(all the bogus stuff was from merging with taxa, so we can index by og dimensions)
merged_dat <- data.frame(response_taxon,
                         merged_dat[,1:length(names(X))])
table(merged_dat$sample %in% taxa$sample)

#######################
# Making variable for stratification #
######################

#Make a one hot variable that is a 1 if the focal taxon (the response variable)
#is present above its median abund. and a zero otherwise. 
#This lets us stratify during splitting so we don't end up with a 
#train/test split that has just high or low values of the response. 

merged_dat$focal_one_hot <- ifelse(response_taxon > median(response_taxon), 1, 0)
table(merged_dat$focal_one_hot)

merged_dat$stratify <- paste(merged_dat$compartment, merged_dat$focal_one_hot)

#remove our bookkeeping data and various unneeded fields
to here this needs work
merged_dat <- merged_dat[,names(merged_dat) %in%
                          c("response_taxon",
                            "sample" ,
                          "absorbance_420",
                         "absorbance_940", 
                         "area_cm2",
                         "Ambient_Humidity",
                         "Ambient_Temperature",
                         "B",
                         "circumStem",
                         "contactless_temp",
                         "deadDown",
                         "densitometer.y",
                         "ecs_initial",
                         "ecs_max",
                         "elev_m",
                         "FmPrime",
                         "FoPrime",
                         "Fs",
                         "FvP.FmP",
                         "G",
                         "gH.",
                         "habit", 
                         "height_sample",
                         "julianDate",
                         "Latitude",
                         "Leaf_Temp_Differential",
                         "LEF",
                         "leaves_extracted",
                         "Light_Intensity..PAR.",
                         "Longitude",
                         "mass_extracted_g",
                         "mean_temp_april.y" ,          
                         "MEM1.y",
                         "MEM2.y",
                         "NPQt_MPF",
                         "phenology",
                         "Phi2",
                         "PhiNO",
                         "PhiNPQ",
                         "plant_vol",
                         "precip_april_in.x",
                         "pressure",
                         "qL",
                         "R",
                         "Rel_Chl_intensity",
                         "Relative_Chlorophyll",
                         "RFd",
                         "sample",
                         "shannons_flora.y",
                         "shrubRich",
                         #"sidePlantSampled",
                         "sla",
                         "slope_perc",
                         "SPAD_420_intensity",
                         "SPAD_420",
                         "thickness",
                         "TimeofDay",
                         "taxon_final",
                         "toughness",
                         "treeRich",
                         "waterRetention"
                         ,"habit_forb"                                               
                          ,"habit_graminoid"                                          
                          ,"habit_shrub"                                              
                          ,"habit_tree"                                               
                          ,"compartment_EN"                                           
                          ,"compartment_EP"                                           
                          ,"taxon_final_Abies.concolor"                               
                          ,"taxon_final_Abies.grandis"                                
                          ,"taxon_final_Antennaria.media"                             
                          ,"taxon_final_Aquilegia.caerula"                            
                          ,"taxon_final_Arnica.cordifolia"                            
                          ,"taxon_final_Artemisia.tridentata"                         
                          ,"taxon_final_Astragalus.alpinus"                           
                          ,"taxon_final_Astragalus.kentrophyta"                       
                          ,"taxon_final_Astragalus.kentrophyta.cf.."                  
                          ,"taxon_final_Astragalus.miser"                             
                          ,"taxon_final_Bistorta.bistortoides"                        
                          ,"taxon_final_Carex.paysonis"                               
                          ,"taxon_final_Carex.scopulorum.var..bracteosa"              
                          ,"taxon_final_Chamaenerion.angustifolium.var..angustifolium"
                          ,"taxon_final_Delphinium.occidentale"                       
                          ,"taxon_final_Erigeron.glacialis"                           
                          ,"taxon_final_Eriogonum.umbellatum"                         
                          ,"taxon_final_Eucephalus.elegans"                           
                          ,"taxon_final_Eucephalus.engelmannii"                       
                          ,"taxon_final_Fragaria.virginiana"                          
                          ,"taxon_final_Frasera.speciosa"                             
                          ,"taxon_final_Geranium.viscossimum.var..viscosissimum"      
                          ,"taxon_final_Helianthella.uniflora"                        
                          ,"taxon_final_Heracleum.maximum"                            
                          ,"taxon_final_Juncus.balticus."                             
                          ,"taxon_final_Juncus.parryi"                                
                          ,"taxon_final_Juncus.sp."                                   
                          ,"taxon_final_Juniperus.communis"                           
                          ,"taxon_final_Ligusticum.filicinum"                         
                          ,"taxon_final_Lupinus.argenteus"                            
                          ,"taxon_final_Mahonia.repens"                               
                          ,"taxon_final_Mertensiana.ciliata.var..ciliata"             
                          ,"taxon_final_Minuartia.obtusiloba"                         
                          ,"taxon_final_Osmorhiza.depauperata"                        
                          ,"taxon_final_Oxyria.digyna"                                
                          ,"taxon_final_Paxistima.myrsinites"                         
                          ,"taxon_final_Picea.engelmannii"                            
                          ,"taxon_final_Pinus.albicaulis"                             
                          ,"taxon_final_Pinus.contorta"                               
                          ,"taxon_final_Poa.pratensis"                                
                          ,"taxon_final_Poa.wheeleri"                                 
                          ,"taxon_final_Polemonium.viscosum"                          
                          ,"taxon_final_Populus.angustifolium"                        
                          ,"taxon_final_Populus.tremulloides"                         
                          ,"taxon_final_Potentilla.diversifolia"                      
                          ,"taxon_final_Potentilla.fruticosa"                         
                          ,"taxon_final_Potentilla.pulcherrima"                       
                          ,"taxon_final_Primula.parryi"                               
                          ,"taxon_final_Pseudotsuga.menziesii"                        
                          ,"taxon_final_Ribes.montigenum"                             
                          ,"taxon_final_Salix.glauca.var..villosa"                    
                          ,"taxon_final_Salix.reticulata.var..nana"                   
                          ,"taxon_final_Sedum.lanceolatum"                            
                          ,"taxon_final_Symphoricarpos.albus"                         
                          ,"taxon_final_Symphyotrichum.foliaceum.var..apricum"        
                          ,"taxon_final_Thalictrum.occidentale"                       
                          ,"taxon_final_Trifolium.parryi.var..montanense"             
                          ,"taxon_final_Unknown.fir"                                  
                          ,"taxon_final_Unknown.pine"                                 
                          ,"taxon_final_Unknown.spruce"                               
                          ,"taxon_final_Unknown.Spruce"                               
                          ,"taxon_final_Vaccinium.membranaceum.__"                 
                          ,"taxon_final_Vaccinium.scoparium"                          
                          ,"taxon_final_Wyethia.amplexicaulis"                        
                          ,"phenology_flowering"                                      
                          ,"phenology_fruiting"                                       
                          ,"phenology_vegetative"                                     
                          ,"stratify" 
                         )]


#########################################
#Use mlr to define a task and a learner#
########################################

#Tasks are a way to organize data and the learner is th emodel 
#see: https://mlr3book.mlr-org.com/tasks.html
phyllo_task = as_task_regr(merged_dat
  , target = "response_taxon", id = "phyllo_data")
phyllo_task

# Create an xgboost learner
learner <- lrn("regr.xgboost", 
               objective = "reg:squarederror")

###############################
#Desccribe resampling strategy. 
##############################
#Resampling is repeated splitting of ALL the data into different train and test sets. 
#the model is trained on each of these training sets and used to predict each of the test sets
#model performance is aggregated across each of these runs. 
#the idea is that we will get a better estimate of model performance. 
#We want to ensure that resampling selects data that are representative of the whole, hence we 
#stratify sampling by important features. 
#THIS IS NOT THE SAME as a train/test split for applying the model to real life data. 
#It is a way to get as unbiased as possible an estimate of how good the model can probably do. 

#Here is a good discussion: https://www.tidymodels.org/learn/work/nested-resampling/
#AND here: https://mlr-org.com/docs/cv-vs-predict/

#We will stratify via our stratification variable
phyllo_task$col_roles$stratum <- "merged_dat.stratify"
phyllo_task$col_roles$name <- "samplename" 
phyllo_task$col_roles$feature <- names(merged_dat)[2:119]

resampling = rsmp("cv", folds = 5)
resampling$instantiate(phyllo_task)

#SANITY CHECK
#check to see how well our stratification worked
#.I is a data.table ism. I took this code from mlr3s website. Don't fully understand
#the data.table isms, but it works.
# dt = merge(resampling$instance, phyllo_task$data()[, row_id := .I], by = "row_id")
# focal_one_hot <- ifelse(dt$response_taxon > median(dt$response_taxon), 1, 0)
# stratificatioFeat <- paste(dt$EN,focal_one_hot)
# table(dt$fold, stratificatioFeat)

#Resample stratifies appropriately whether the stratification feature has role of "feature" or not.

#####################
# Feature selection #
#####################
#https://mlr3book.mlr-org.com/fs.html

feat_selector = FSelectInstanceSingleCrit$new(
  task = phyllo_task,
  learner = learner,
  resampling = rsmp("loo"),
  measure = msr("regr.rsq"),
  terminator = trm("stagnation")
)
#fselector = fs("rfe")
fselector = fs("sequential")

# reduce logging output
lgr::get_logger("bbotk")$set_threshold("warn")

fselector$optimize(feat_selector)
#See what we are left with
feat_selector$result_feature_set

phyllo_task$select(feat_selector$result_feature_set)

##########
# tuning #
##########

#define hyperparameters to check via CV
params <- ps(
  eta = p_dbl(lower = 0.1, upper = 0.3),
  nrounds = p_int(lower = 1, upper = 16, tags = "budget"),
  booster = p_fct(levels = c("gbtree", "gblinear", "dart")),
  gamma = p_int(lower = 0, upper = 5),
  max_depth = p_int(lower = 4, upper = 15),
  min_child_weight = p_int(lower = 1, upper = 10),
  subsample = p_dbl(lower = 0.5, upper = 0.8),
  colsample_bytree = p_dbl(lower = 0.5, upper = 1)
)

instance = TuningInstanceSingleCrit$new(
  task = phyllo_task,
  learner = learner,
  resampling = resampling,
  measure = msr("regr.rsq"),
  search_space = params,
  terminator = trm("none") # hyperband terminates itself
)

tuner = tnr("hyperband", eta = 3) #eta is how many models advance to next round

#Do tuning
# reduce logging output
lgr::get_logger("bbotk")$set_threshold("warn")

tuner$optimize(instance)

#best results
instance$result
learner$param_set$values = instance$result_learner_param_vals
learner$train(phyllo_task)
learner$predict(phyllo_task)

cor.test(learner$predict(phyllo_task)$truth, 
         learner$predict(phyllo_task)$response)

###################################################
# Nested resampling to estimate model performance #
###################################################

at = AutoTuner$new(
  learner = learner,
  resampling = rsmp("holdout"),
  measure = msr("regr.rsq"),
  terminator = trm("none"),
  tuner = tnr("hyperband", eta = 3),
  search_space = params)

#pass back to resampling for nested resampling
 outer_resampling = rsmp("cv", folds = 5)
 rr = resample(task = phyllo_task, 
               learner = at, 
               outer_resampling, 
              
               store_models = TRUE)
 
outer_resampling$instantiate(phyllo_task)

extract_inner_tuning_results(rr)

# #outer tuning results
rr$score()

#This is the unbiased estimate of model performance
rsq <- rr$aggregate( measure = msr("regr.rsq")) #can swap out different measures
mse <- rr$aggregate(measure = msr("regr.mse") ) #can swap out different measures

save(file = paste("./models/ITSxgboost", focal_taxon, ".Rdata", sep = ""))
##################################################################
# Extract important features
##################################################################

out <- data.frame(xgb.importance(model = learner$model))
out$taxon <- focal_taxon
out$rsq_nested_resampling <- rsq
out$mse_nested_resampling <- mse

write.csv(out, file = paste("./models/ITSxgboost", focal_taxon, "results.csv", sep = ""))


#4. SHAP?

