#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 29 14:04:34 2021

@author: jharrison
"""

import pandas as pd
pd.set_option('display.max_rows', None)

#Bring in taxon proportions, these were wrangled in R after being generated by CNVRG
taxa = pd.read_csv("./processedData/ITS_otu_table_preModeling.csv")

#Choose all taxa that are present in at least 200 samples.
#Note we are going to use the raw data, not the proportion data
#this seems easier to work with for this purpose since proportion data
#will never be zero. It seems simpler to use raw data to find an 
#arbitrary threshold for taxon prevalence such that we want to model them. 

def determine_prevalence(taxa):
    taxon_list = list()
    for taxon in taxa.iloc[:,2:].columns:
        # list comprehension
        # to get numbers > k
        count = len([i for i in taxa[taxon] if i > 1])
        if count >= 100:
            if taxon not in ('duds','ISD', 'plant', 'mtDNA'):
                taxon_list.append(taxon)
    return taxon_list


taxon_list = determine_prevalence(taxa)

len(taxon_list) #177

taxon_list = pd.DataFrame(taxon_list, columns=["taxa_its"])

taxon_list.to_csv(path_or_buf=("./processedData/ITS_taxa_to_model_via_randomforest.csv"), index=False)

#Do for bacteria
bacts = pd.read_csv("./processedData/sixteenS_otu_table_preModeling.csv")
bacts_list = determine_prevalence(bacts)

bacts_list = pd.DataFrame(bacts_list, columns=["taxa_16s"])

bacts_list.to_csv(path_or_buf=("./processedData/sixteenS_taxa_to_model_via_randomforest.csv"), index=False)
